FROM node:14-alpine as build

WORKDIR /app

COPY . /app

ENV PATH /app/node_modules/.bin:$PATH

# Get env from github actions variables
ARG ARG_API_URL
ENV REACT_APP_BASE_URL=$ARG_API_URL

ARG ARG_GOOGLE_MAPS_KEY
ENV REACT_APP_GOOGLE_MAPS_KEY=$ARG_GOOGLE_MAPS_KEY

RUN yarn install

RUN yarn build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]