name: CI mihealthcare-admin

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

    steps:
      # this workflow needs app source and Dockerfile to build image
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # identify commit
      - name: Print commit id and message
        run: |
          git show -s --format='%h %s'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.prod
          build-args: |
            "ARG_API_URL=${{ secrets.ARG_API_URL }}"
            "ARG_GOOGLE_MAPS_KEY=${{ secrets.ARG_GOOGLE_MAPS_KEY }}"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mihealthcare-admin

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: SSH to host and Pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/mihealthcare-admin --format="{{.ID}}"))
            docker rmi ${{ secrets.DOCKER_USERNAME }}/mihealthcare-admin:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/mihealthcare-admin
            docker run -d -p 5000:80 ${{ secrets.DOCKER_USERNAME }}/mihealthcare-admin
